### ISSUE TITLE
Ajouter le fichier de calibration du velodyne

### ISSUE THREAD

**Issue by jefft255** [norlab-ulaval/husky-config#2]
Pour lancher le node velodyne_pointcloud, http://wiki.ros.org/velodyne_pointcloud?distro=groovy#transform_node on a besoin d'un fichier de calibration .yaml de notre capteur. Je ne crois pas que ce fichier est dans un de nos repos. Il est sur le husky.

**Comment by PhiBabin** [comment]
Il est pas inclue dans le dépot? 
https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/params/32db.yaml

**Comment by jefft255** [comment]
Oui, my bad. Je pensais qu'il y avait des paramètres de calibration spécifiques à chaque capteurs la dedans.
